[project]
name = "personal-architecture"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "fabric>=3.2.2",
    "jsonschema>=4.23.0",
    "requests>=2.32.3",
]
