---
# Install WireGuard on Debian/Ubuntu

- name: Update apt cache
  apt:
    update_cache: yes
    cache_valid_time: 3600
  become: true

- name: Install WireGuard and dependencies
  apt:
    name:
      - wireguard
      - wireguard-tools
      - iptables
      - resolvconf
    state: present
  become: true 