---
# Install WireGuard on RedHat/CentOS

- name: Install EPEL repository
  yum:
    name: epel-release
    state: present
  become: true

- name: Install WireGuard and dependencies
  yum:
    name:
      - wireguard-tools
      - iptables
    state: present
  become: true

- name: Install kernel module (CentOS 8/RHEL 8)
  yum:
    name: kmod-wireguard
    state: present
  become: true
  when: ansible_distribution_major_version == "8"
  ignore_errors: yes 