---
redhat_dependencies:
  - git
  - gcc
  - gcc-c++
  - pkg-config
  - meson
  - glib2-devel
  - jsoncpp-devel
  - libuuid-devel
  - lz4-devel
  - libcap-ng-devel
  - libxml2
  - python3
  - python3-dbus
  - python3-docutils
  - python3-jinja2
  - tinyxml2-devel
  - polkit
  - systemd-devel
  - python3-systemd
  - openssl-devel
  - openssl-libs
  - dbus-devel
  - cmake
  - unzip
  - libnl3
  - libnl3-devel

# Optional dependencies for DCO support
dco_dependencies:
  - libnl3-devel
  - protobuf-compiler
  - protobuf-devel 